name: CD

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup JDK 14
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14

      - name: Setup Gradle Cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build Backend
        run: ./gradlew jibDockerBuild
        env:
          DOCKER_BUILDKIT: 1

      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
          docker tag kortance docker.pkg.github.com/smartsquaregmbh/kortance/kortance:$VERSION

          docker push docker.pkg.github.com/smartsquaregmbh/kortance/kortance:$VERSION
        env:
          VERSION: ${{ github.event.release.tag_name }}
