name: CD

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup JDK 14
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14

      - name: Setup Gradle Cache
        uses: actions/cache@v2.1.2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build native-image
        run: ./gradlew nativeImage
        env:
          DOCKER_BUILDKIT: 1

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/graal/kortance
          asset_name: kortance-${{ matrix.os }}
          tag: ${{ github.ref }}
          overwrite: true
