name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup JDK 14
        uses: actions/setup-java@v1.4.0
        with:
          java-version: 14

      - name: Setup Gradle cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Check
        run: ./gradlew check

      - name: Upload Gradle reports
        uses: actions/upload-artifact@v2.1.3
        if: failure()
        with:
          name: Gradle Reports
          path: "**/build/reports"
